'use strict';
const menu=[
 {id:'burger',name:'Wagyu Signature Burger',short:'Signature Burger',price:65,category:'SIGNATURE / WITH FRIES',description:'Double beef, cheddar, tomato and lettuce in brioche, with golden fries.',allergens:'wheat, milk, egg'},
 {id:'pasta',name:'Black Truffle Pasta',short:'Truffle Pasta',price:72,category:'PASTA / VEGETARIAN',description:'A nest of golden pasta ribbons with creamy parmesan, black truffle and fresh herbs.',allergens:'wheat, milk, egg'},
 {id:'shrimp',name:'Dynamite Shrimp',short:'Dynamite Shrimp',price:54,category:'SMALL PLATES / SEAFOOD',description:'Curled prawns in a warm, spicy dynamite glaze, finished with fresh herbs.',allergens:'crustaceans, wheat, egg'},
 {id:'salmon',name:'Charred Atlantic Salmon',short:'Charred Salmon',price:89,category:'MAINS / SEAFOOD',description:'A charred salmon fillet with green asparagus and a bright slice of lemon.',allergens:'fish, milk'},
 {id:'dessert',name:'Chocolate Lava',short:'Chocolate Lava',price:42,category:'SOMETHING SWEET',description:'A dark chocolate fondant with molten chocolate and a scoop of vanilla ice cream.',allergens:'wheat, milk, egg'}
];
const $=id=>document.getElementById(id),viewer=$('viewer');let current='burger',loadTimer,toastTimer;
const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const fallback=document.createElement('img');fallback.className='model-fallback';fallback.alt='Static preview while interactive 3D loads';viewer.before(fallback);
const iosAR=document.createElement('a');iosAR.id='iosAR';iosAR.rel='ar';iosAR.className='ios-ar';iosAR.hidden=!isIOS;iosAR.innerHTML='<img src="assets/burger.png" alt="">Place on your table ↗';$('ar').after(iosAR);
if(isIOS)$('ar').hidden=true;
const probe=document.createElement('canvas');let webglOK=false;try{const gl=probe.getContext('webgl2');webglOK=Boolean(gl);if(gl)gl.getExtension('WEBGL_lose_context')?.loseContext()}catch{}
const canonical=new URL('./',location.href);canonical.search='';canonical.hash='';
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',5000)}
function fail(message){$('loading').hidden=false;$('loading').textContent=message;$('retry').hidden=false;$('ar').disabled=true;$('ar').textContent='3D unavailable';clearTimeout(loadTimer)}
function loading(){fallback.hidden=false;$('loading').hidden=false;$('loading').textContent='Preparing your plate…';$('retry').hidden=true;$('ar').disabled=true;$('ar').textContent='Loading 3D…';clearTimeout(loadTimer);if(!webglOK){fail('Interactive 3D is unavailable in this browser. Showing a static preview. Open in Safari or Chrome.');$('retry').hidden=true;return}loadTimer=setTimeout(()=>fail('The model is taking longer than expected. Check your connection and tap Retry.'),30000)}
function updateAR(){if(!viewer.loaded)return;$('ar').disabled=false;const available=viewer.canActivateAR;$('ar').textContent=available?'Place on your table ↗':'How to view in AR';$('arHelp').textContent=available?'Tap to open AR. On iPhone, choose AR in Quick Look and move your phone slowly over a well-lit table.':'3D is ready. For camera AR, open this page in Safari on iPhone or Chrome on an AR-supported Android phone. In-app browsers may not support AR.'}
function choose(id,changeURL=true){const dish=menu.find(d=>d.id===id)||menu[0];current=dish.id;fallback.src='assets/'+current+'.png';iosAR.href='assets/'+current+'.usdz#allowsContentScaling=0';iosAR.querySelector('img').src=fallback.src;viewer.setAttribute('ios-src','assets/'+current+'.usdz');document.querySelectorAll('.dish-choice').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===current)));$('dishName').textContent=dish.name;$('category').textContent=dish.category;$('description').textContent=dish.description;$('allergens').textContent='Contains: '+dish.allergens+'.';$('price').textContent='AED '+dish.price;$('dishNumber').textContent=String(menu.indexOf(dish)+1).padStart(2,'0')+' / 05';viewer.alt=dish.name+', stylised interactive 3D preview';viewer.cameraOrbit='35deg 65deg auto';if(viewer.getAttribute('src')!=='assets/'+current+'.glb?v=3'){loading();viewer.setAttribute('src','assets/'+current+'.glb?v=3')}else if(viewer.loaded){updateAR()}document.title='SABOR — '+dish.name;if(changeURL)history.replaceState(null,'','#'+current)}
menu.forEach((dish,i)=>{const button=document.createElement('button');button.className='dish-choice';button.dataset.id=dish.id;button.setAttribute('aria-pressed','false');button.innerHTML='<span><small>'+String(i+1).padStart(2,'0')+'</small>'+dish.short+'</span><span>AED '+dish.price+'</span>';button.addEventListener('click',()=>choose(dish.id));$('dishes').append(button)});
viewer.addEventListener('load',()=>{clearTimeout(loadTimer);fallback.hidden=true;$('loading').hidden=true;$('retry').hidden=true;updateAR()});viewer.addEventListener('error',()=>fail('Interactive 3D could not load. Try opening directly in Safari or Chrome.'));
viewer.addEventListener('ar-status',event=>{if(event.detail.status==='failed'){$('arHelp').textContent='AR could not start. Open this link in Safari (iPhone) or Chrome (Android), then try again.';toast('AR could not start in this browser.')}});
$('ar').addEventListener('click',async()=>{if(!viewer.canActivateAR){toast('Open in Safari on iPhone, or Chrome on an AR-supported Android phone.');return}try{await viewer.activateAR()}catch(e){$('arHelp').textContent='AR could not start. Open this page directly in Safari or Chrome and try again.'}});
$('retry').addEventListener('click',()=>{loading();viewer.src='assets/'+current+'.glb?retry='+Date.now()});
$('rotate').addEventListener('click',()=>{viewer.autoRotate=!viewer.autoRotate;$('rotate').textContent=viewer.autoRotate?'Pause rotation':'Resume rotation';$('rotate').setAttribute('aria-pressed',String(viewer.autoRotate))});
$('share').addEventListener('click',async()=>{const data={title:'SABOR — The 3D Menu',text:'Explore your next craving in 3D and AR.',url:canonical.href};try{if(navigator.share){await navigator.share(data)}else if(navigator.clipboard){await navigator.clipboard.writeText(data.url);toast('Menu link copied')}else{toast(data.url)}}catch(e){if(e.name!=='AbortError')toast('Share this address: '+data.url)}});
loading();choose(location.hash.slice(1)||new URLSearchParams(location.search).get('dish')||'burger',false);window.addEventListener('hashchange',()=>choose(location.hash.slice(1),false));
customElements.whenDefined('model-viewer').then(()=>{if(viewer.loaded){$('loading').hidden=true;clearTimeout(loadTimer);updateAR()}});
