'use strict';
const menu=[
 {id:'burger',name:'Wagyu Signature Burger',short:'Signature Burger',price:65,category:'SIGNATURE / WITH FRIES',description:'Two juicy beef patties, molten cheddar, crisp lettuce and tomato in a toasted brioche bun. Golden fries on the side.',allergens:'wheat, milk and egg'},
 {id:'pasta',name:'Black Truffle Pasta',short:'Truffle Pasta',price:72,category:'PASTA / VEGETARIAN',description:'Fresh golden ribbons folded through parmesan cream, finished with generous black truffle shavings and delicate herbs.',allergens:'wheat, milk and egg'},
 {id:'shrimp',name:'Dynamite Shrimp',short:'Dynamite Shrimp',price:54,category:'SMALL PLATES / SEAFOOD',description:'Crisp golden prawns tossed in a glossy, gently spicy dynamite sauce, with sesame and fresh scallions.',allergens:'crustaceans, wheat, egg and sesame'},
 {id:'salmon',name:'Charred Atlantic Salmon',short:'Charred Salmon',price:89,category:'MAINS / SEAFOOD',description:'A beautifully seared salmon fillet, tender green asparagus, charred lemon and a silky lemon-butter finish.',allergens:'fish and milk'},
 {id:'dessert',name:'Chocolate Lava',short:'Chocolate Lava',price:42,category:'SOMETHING SWEET',description:'Warm dark chocolate fondant with a molten centre, cool vanilla ice cream and a delicate dusting of cocoa.',allergens:'wheat, milk and egg'}
];
const $=id=>document.getElementById(id),isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const isAndroid=/Android/i.test(navigator.userAgent);
let current='burger',mode='photo',viewer=null,modulePromise=null,loadTimer,toastTimer,requestId=0;
const photo=id=>'assets/'+id+'-photo.webp';
const arDisclaimer='AR uses this dish image on a tabletop photo plaque.';
const canonical=new URL('./',location.href);canonical.search='';canonical.hash='';
$('iosAR').hidden=!isIOS;$('androidAR').hidden=!isAndroid;$('ar').hidden=isIOS||isAndroid;
function configureAR(dish){
 const fallback=new URL(canonical.href);fallback.searchParams.set('ar','unavailable');fallback.hash=dish.id;
 const model=new URL('assets/'+dish.id+'.glb?v=6',canonical);
 $('androidAR').href='intent://arvr.google.com/scene-viewer/1.0?file='+encodeURIComponent(model.href)+'&mode=ar_preferred&title='+encodeURIComponent(dish.name)+'#Intent;scheme=https;package=com.google.android.googlequicksearchbox;action=android.intent.action.VIEW;S.browser_fallback_url='+encodeURIComponent(fallback.href)+';end;';
 $('arHelp').textContent=(new URLSearchParams(location.search).get('ar')==='unavailable'?'AR could not open on this device. Try Chrome on an AR-supported Android phone. ':isIOS?'Open in Safari, then tap View on your table. ':isAndroid?'Tap View on your table to open the native AR viewer. ':'Scan the QR code below with your phone for camera AR. ')+arDisclaimer;
}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000)}
function status(message,retry=false){$('modelStatus').textContent=message;$('modelStatus').hidden=!message;$('retry').hidden=!retry}
function showPhoto(){requestId++;clearTimeout(loadTimer);mode='photo';$('modelHost').hidden=true;$('dishPhoto').hidden=false;$('stage').classList.remove('show-model');$('modelStatus').hidden=true;$('rotate').hidden=true;$('retry').hidden=true;$('photoMode').setAttribute('aria-pressed','true');$('modelMode').setAttribute('aria-pressed','false');$('visualLabel').textContent='SIGNATURE COLLECTION';$('visualHint').textContent='A closer look at your next favourite.';if(viewer)viewer.autoRotate=false}
function library(){if(!modulePromise)modulePromise=import('https://ajax.googleapis.com/ajax/libs/model-viewer/4.1.0/model-viewer.min.js').catch(e=>{modulePromise=null;throw e});return modulePromise}
function armTimeout(){clearTimeout(loadTimer);loadTimer=setTimeout(()=>{if(mode==='model')status('The 3D preview is taking longer than expected. You can return to the photo or retry.',true)},30000)}
function buildViewer(){const element=document.createElement('model-viewer');element.id='viewer';for(const [key,value] of Object.entries({'camera-controls':'','touch-action':'pan-y','auto-rotate':'','rotation-per-second':'14deg','shadow-intensity':'1','environment-image':'neutral','camera-orbit':'0deg 80deg auto','field-of-view':'35deg','ar':'','ar-modes':'webxr scene-viewer quick-look','ar-scale':'fixed'}))element.setAttribute(key,value);element.addEventListener('load',()=>{clearTimeout(loadTimer);status('');$('ar').disabled=false;$('ar').textContent='View on your table ↗'});element.addEventListener('error',()=>{clearTimeout(loadTimer);status('This 3D preview could not load. Return to the photo or try again.',true)});element.addEventListener('ar-status',e=>{if(e.detail.status==='failed')toast('Open this menu in Safari on iPhone or Chrome on a supported Android phone.')});$('modelHost').append(element);return element}
function modelFailure(message){showPhoto();$('arHelp').textContent=message+' '+arDisclaimer;toast(message)}
async function showModel(){const request=++requestId;mode='model';$('modelHost').hidden=false;$('dishPhoto').hidden=true;$('stage').classList.add('show-model');$('photoMode').setAttribute('aria-pressed','false');$('modelMode').setAttribute('aria-pressed','true');$('visualLabel').textContent='PHOTO-TEXTURED 3D PREVIEW';$('visualHint').textContent='Drag to rotate · pinch or scroll to zoom';status('Loading the 3D preview…');armTimeout();
 try{const canvas=document.createElement('canvas'),gl=canvas.getContext('webgl2');if(!gl){modelFailure('Interactive 3D is unavailable in this browser. You can still use the phone AR button.');return}gl.getExtension('WEBGL_lose_context')?.loseContext();await library();if(mode!=='model'||request!==requestId)return;if(!viewer)viewer=buildViewer();const path='assets/'+current+'.glb?v=6';viewer.setAttribute('ios-src','assets/'+current+'.usdz?v=6');viewer.alt=menu.find(d=>d.id===current).name+', photo-textured 3D preview';viewer.autoRotate=true;$('rotate').hidden=false;$('rotate').textContent='Pause rotation';$('rotate').setAttribute('aria-pressed','true');if(viewer.getAttribute('src')!==path){viewer.src=path}else if(viewer.loaded){clearTimeout(loadTimer);status('')}}catch(e){if(request!==requestId)return;modelFailure('The 3D viewer could not start. Your dish photo is still available.')}}
function choose(id,changeURL=true){const dish=menu.find(d=>d.id===id)||menu[0];current=dish.id;showPhoto();$('dishPhoto').src=photo(current);$('dishPhoto').alt=dish.name+' — AI-created food image';$('iosAR').href='assets/'+current+'.usdz?v=6#allowsContentScaling=0';$('iosAR').querySelector('img').src=photo(current);$('dishName').textContent=dish.name;$('category').textContent=dish.category;$('description').textContent=dish.description;$('allergens').textContent='Contains '+dish.allergens+'.';$('price').innerHTML='<small>AED</small> '+dish.price;$('dishNumber').textContent=String(menu.indexOf(dish)+1).padStart(2,'0')+' / 05';configureAR(dish);$('ar').disabled=false;document.querySelectorAll('.dish-choice').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===current)));document.title='SABOR — '+dish.name;if(changeURL)history.replaceState(null,'','#'+current)}
menu.forEach((dish,i)=>{const b=document.createElement('button');b.className='dish-choice';b.dataset.id=dish.id;b.setAttribute('aria-pressed','false');b.innerHTML='<img src="'+photo(dish.id)+'" width="84" height="72" alt="" loading="'+(i?'lazy':'eager')+'"><span class="choice-copy"><small>'+String(i+1).padStart(2,'0')+' / '+dish.category.split(' / ')[0]+'</small><span>'+dish.short+'</span></span><span class="choice-price">AED '+dish.price+'</span>';b.addEventListener('click',()=>choose(dish.id));$('dishes').append(b)});
$('photoMode').addEventListener('click',showPhoto);$('modelMode').addEventListener('click',showModel);$('retry').addEventListener('click',()=>{if(viewer)viewer.removeAttribute('src');showModel()});
$('rotate').addEventListener('click',()=>{if(!viewer)return;viewer.autoRotate=!viewer.autoRotate;$('rotate').textContent=viewer.autoRotate?'Pause rotation':'Resume rotation';$('rotate').setAttribute('aria-pressed',String(viewer.autoRotate))});
$('ar').addEventListener('click',()=>{document.querySelector('.share-block').scrollIntoView({behavior:'smooth',block:'center'});toast('Scan the QR code with your phone, open in Safari or Chrome, and select your dish.');});
$('share').addEventListener('click',async()=>{const data={title:'SABOR — The Signature Menu',text:'A closer look at your next favourite.',url:canonical.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast('Menu link copied')}}catch(e){if(e.name!=='AbortError')toast('Share this address: '+data.url)}});
choose(location.hash.slice(1)||new URLSearchParams(location.search).get('dish')||'burger',false);window.addEventListener('hashchange',()=>choose(location.hash.slice(1),false));
